services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: amowu-dynamodb
    ports:
      - "8000:8000"
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /data
    volumes:
      - dynamodb-data:/data

volumes:
  dynamodb-data:
