export const SET_ACTIVED_DIALOGUE = 'SET_ACTIVED_DIALOGUE'

export const FETCH_USER_RESUME_ERROR = 'FETCH_USER_RESUME_ERROR'
export const FETCH_USER_RESUME_START = 'FETCH_USER_RESUME_START'
export const FETCH_USER_RESUME_SUCCESS = 'FETCH_USER_RESUME_SUCCESS'
